version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay:classes
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-testpage-overlay
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-client
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-structures-r4
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-validation-resources-r4
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-base
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-jpaserver-base
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-jaxrsserver-base
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-spring-boot-autoconfigure
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: ca.uhn.hapi.fhir:hapi-fhir-spring-boot-starter
    versions:
    - 5.3.0
    - 5.3.2
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-configuration-processor
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-data-jpa
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-jersey
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-actuator
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
